/**
 * Typed browser-side wrapper for the K-11 diagnostics API.
 *
 * The two endpoints consumed here are:
 *   • `POST /api/diagnose` — returns the K-11 posterior score + 94% HDI for a
 *     single track, given its 11 features and a K-11 genre. Validated with
 *     Zod on the server (see `src/app/api/diagnose/route.ts`).
 *   • `GET  /api/generos`  — returns the 107 K-11 genre labels from
 *     `artifacts/genero_cats.json`, used to populate the manual override
 *     dropdown for short audio clips.
 *
 * Both calls are `cache: "no-store"` so the client never reuses a previous
 * response and always hits the server fresh — important because the LLM
 * explanation in `/api/diagnose` is non-deterministic and the user expects
 * to see the current latency / score, not a cached one.
 */

// `Prediction` is intentionally re-exported alongside `TrackFeatures` so the
// UploadAnalyzer can keep all K-11 types flowing from a single import path
// (`@/lib/k11Client`); the runtime contracts here only depend on
// `TrackFeatures`, but the type surface stays consistent.
import type { TrackFeatures, Prediction } from "@/lib/types";

/**
 * Successful response body from `POST /api/diagnose`.
 *
 * Mirrors the JSON returned by `src/app/app/api/diagnose/route.ts` line 79-85:
 *   { score, hdi_94: [prediction.hdi_lo, prediction.hdi_hi], explicacao,
 *     genero, ms_per_call }
 *
 * `hdi_94` is a 94% Highest Density Interval over the 1000 posterior samples
 * — i.e. the range in which the true popularity-score sits with 94%
 * probability. Always `lo <= hi` and both lie within `[0, 100]`.
 */
export type DiagnoseResponse = {
  /** K-11 predicted popularity score, integer 0..100. */
  score: number;
  /** 94% HDI lower and upper bounds, both integer 0..100. */
  hdi_94: [number, number];
  /** PT-BR natural-language explanation generated by the OpenRouter LLM
   *  (or fallback message if LLM is unavailable — see `explicacao_source`). */
  explicacao: string;
  /** Wave 4 M3: explicit flag telling the client whether `explicacao` came
   *  from the real LLM or from a deterministic fallback message. Useful
   *  for clients/dashboards to distinguish real vs degraded operation. */
  explicacao_source: "llm" | "fallback";
  /** Echoed K-11 genre label (one of the 107 from genero_cats.json). */
  genero: string;
  /** Server-side wall-clock time of the whole call, in milliseconds. */
  ms_per_call: number;
};

/**
 * Error response body shape. The server can return either:
 *   • `{ error: "Validation failed", details: ZodFlattenedError }` (400)
 *   • `{ error: "Unknown genre: ...", valid_generos: string[] }` (400)
 *   • `{ error: "..." }` (500 — predict/loadGz failure)
 *
 * We treat `details` as `unknown` because Zod's `flatten()` returns a
 * deeply-nested object we don't need to model on the client.
 */
export type DiagnoseError = {
  /** Human-readable error message, safe to surface to the user. */
  error: string;
  /** Present only on `Unknown genre` 400 — full list of 107 valid K-11 genres. */
  valid_generos?: string[];
  /** Present only on `Validation failed` 400 — Zod-flattened error tree. */
  details?: unknown;
};

/**
 * Calls `POST /api/diagnose` with the track's 11 features and a K-11 genre.
 *
 * @param features - 11-dimensional feature vector (10 Q8 + `mode_bin`) as
 *                   produced by `extractK11Features()`. Numeric ranges are
 *                   enforced server-side via Zod.
 * @param genero   - K-11 genre label. Must be one of the 107 from
 *                   `artifacts/genero_cats.json`. Use `fetchGeneros()` to
 *                   enumerate them, or `bridgeGenre(gtzanTop1)` from
 *                   `src/lib/genreBridge.ts` to map from the GTZAN-10.
 * @returns Parsed `DiagnoseResponse` on 2xx.
 * @throws `Error` with `error.message` from the server on 4xx/5xx, or
 *         `Error("HTTP <status>")` if the body is unparseable. The original
 *         server payload (including `details` / `valid_generos`) is attached
 *         to `error.details` for the caller to inspect — **do not** render
 *         that field to end users, only to logs.
 *
 * @example
 * ```ts
 * try {
 *   const resp = await diagnose(k11.features, "pop");
 *   console.log(`K-11 score: ${resp.score} (HDI ${resp.hdi_94[0]}-${resp.hdi_94[1]})`);
 * } catch (err) {
 *   // err.message is safe to show; err.details is for console only.
 *   console.error("diagnose failed", err);
 *   setError(err instanceof Error ? err.message : "Falha desconhecida");
 * }
 * ```
 */
export async function diagnose(
  features: TrackFeatures,
  genero: string,
): Promise<DiagnoseResponse> {
  const response = await fetch("/api/diagnose", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    // `cache: "no-store"` is the default for POST but spelled out for clarity:
    // we never want a stale or browser-cached response here.
    cache: "no-store",
    body: JSON.stringify({ track_features: features, genero }),
  });

  if (response.ok) {
    return (await response.json()) as DiagnoseResponse;
  }

  // Tenta extrair o body de erro (pode ser 400 com { error, valid_generos, details }
  // ou 500 com { error }). Em qualquer caso, surfamos `error` ao usuário e
  // escondemos `details` (log apenas no console).
  let payload: DiagnoseError = { error: `HTTP ${response.status}` };
  try {
    payload = (await response.json()) as DiagnoseError;
  } catch {
    // corpo nao era JSON — mantem o fallback acima
  }

  // Detalhes sensíveis vão pro console para debugging, mas o `Error`
  // lançado carrega apenas a mensagem pública (`payload.error`).
  console.error("[k11Client.diagnose] server error", {
    status: response.status,
    payload,
  });

  const err = new Error(
    payload.error || `Falha no diagnóstico K-11 (HTTP ${response.status})`,
  );
  // anexa o payload bruto para consumidores que queiram inspecionar
  // (ex.: dropdown de override pode ler valid_generos em código).
  (err as Error & { details?: unknown }).details = payload;
  throw err;
}

/**
 * Fetches the full list of 107 K-11 genre labels from `GET /api/generos`.
 *
 * @returns Array of genre strings (e.g. `["pop", "rock", "hip-hop", ...]`).
 * @throws `Error` if the network call fails or the body is malformed.
 *
 * @example
 * ```ts
 * const generos = await fetchGeneros();
 * // populates <select> fallback for clips < 5s where GTZAN returns no genre
 * ```
 */
export async function fetchGeneros(): Promise<string[]> {
  const response = await fetch("/api/generos", {
    method: "GET",
    cache: "no-store",
  });

  if (!response.ok) {
    const err = new Error(`Falha ao listar gêneros K-11 (HTTP ${response.status})`);
    console.error("[k11Client.fetchGeneros] server error", {
      status: response.status,
    });
    throw err;
  }

  const body = (await response.json()) as { generos: string[]; count: number };
  return body.generos;
}

// Re-export `Prediction` so callers using `k11Client` for types don't need
// a second import. Not used at runtime.
export type { TrackFeatures, Prediction };
